name: .NET Core Desktop

on:
  push:
    branches: 
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Execute unit tests
      run: dotnet test --configuration ${{ matrix.configuration }}

  create_pr:
   needs: build
   if: github.ref == 'refs/heads/dev'
   runs-on: windows-latest

   steps:
     - name: Checkout code
       uses: actions/checkout@v4
       with:
         fetch-depth: 0

     - name: Create Pull Request
       run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
         gh pr create --base master --head dev --title "Merge dev into master" --body "Automated PR from dev to master"
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 

  auto_merge:
    needs: [build, create_pr]
    if: github.ref == 'refs/heads/dev'
    runs-on: windows-latest

    name: .NET Core Desktop

on:
  push:
    branches: 
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Execute unit tests
      run: dotnet test --configuration ${{ matrix.configuration }}

  create_pr:
   needs: build
   if: github.ref == 'refs/heads/dev'
   runs-on: windows-latest

   steps:
     - name: Checkout code
       uses: actions/checkout@v4
       with:
         fetch-depth: 0

     - name: Create Pull Request
       run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
         gh pr create --base master --head dev --title "Merge dev into master" --body "Automated PR from dev to master"
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 

  auto_merge:
    needs: [build, create_pr]
    if: github.ref == 'refs/heads/dev'
    runs-on: windows-latest

    steps:
    - name: Auto Merge PR
      if: ${{ github.event.pull_request.merged == false }}
      uses: Igvhore/action-auto-merge@v2.3.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pull_request_number: ${{ github.event.pull_request.number }}
        merge_method: merge
