name: .NET Core Desktop

on:
  push:
    branches: 
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:

  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Execute unit tests
      run: dotnet test --configuration ${{ matrix.configuration }}

  create_pull_request:
    if: github.ref == 'refs/heads/dev' 
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create Pull Request
      id: create_pr 
      uses: Igvhore/CICD@v5 
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: master 
        delete-branch: false
        title: 'Auto PR: Update from development'
        body: 'This is an automated pull request generated by GitHub Actions.'
        draft: false 

  auto_merge:
    needs: create_pull_request 
    runs-on: windows-latest

    steps:
    - name: Auto Merge PR
      if: ${{ steps.create_pr.outputs.pull-request-url != '' }} 
      uses: Igvhore/CICD@v2.3.0 
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pull_request_number: ${{ steps.create_pr.outputs.pull-request-number }} 
        merge_method: merge
