name: Generate Documentation

on:
  push:
    branches:
      - main
      - dev
      - release
  pull_request:
    branches:
      - main
      - dev
      - release

jobs:
  generate_docs:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project and generate documentation
        run: |
          mkdir -p docs
          dotnet build --configuration Release /p:DocumentationFile=docs\Doc.xml

      - name: Verify Documentation
        run: |
          if (Test-Path -Path "docs\Doc.xml") {
            Write-Host "Документ Doc.xml успешно сгенерирован."
          } else {
            Write-Host "Документ Doc.xml не был сгенерирован."
            exit 1
          }
        shell: pwsh
